name: Actualizar API Legislativa

on:
  schedule:
    - cron: '0 11 * * *' # Corre todos los días a las 8 AM (hora Arg aprox)
  workflow_dispatch:      # Permite correrlo a mano con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: pip install pandas requests
      - name: Ejecutar script de carga
        run: python script_carga.py
